### PR TITLE
Remove filenames containing regular expressions

### PR DESCRIPTION
**Pull request by bartbutenaers**
Hey Dean,

I saw a question today on the [forum](https://groups.google.com/forum/#!topic/node-red/qQ9h8-OtmNc) about your node: functionality to be able to remove multiple files at once (by using **wildcards**).

For example I have multiple images in my /tmp folder:
image

I would like to remove all these image files at once, by entering a **regular expression** (image_*\d.png) in the filename field:
image

Not really wildcards, but also very powerfull...

I tried to reuse as much as possible from your existing code.  Hopefully you like the suggested solution.

Thanks in advance for reviewing my changes !!!
Kind regards,
Bart Butenaers

### CODE REVIEW

**Comment by dceejay** [comment]
Surely the . In regular file names now becomes a wildcard in a regex which could be dangerous. If this is implemented it should be a selectable mode of operation

**Comment by bartbutenaers** [comment]
Hi @DeanCording ,

Dave has added some useful information in the discussion on the forum.  Since this might involve much more code changes, I think you should decide whether/how it should be implemented.  If you need any help, please let me know.

Kind regards,
Bart

**Comment by DeanCording** [comment]
Thanks Bart,

Give me a few days to take a look at it.

Dean

**Comment by DeanCording** [comment]
Sorry Bart,  I got side tracked from looking at this.

I've added this functionality but in a different way so that it was consistent with the other fs-ops nodes.  The fs-ops-dir node will return a list of file names filtered by wildcards.  This array can be passed to a couple of other fs-ops nodes like fs-ops-type and fs-ops-size.  I've added the functionality to fs-ops-delete so you can use fs-ops-dir to find the files and pass them to fs-ops-delete to delete them.

**Comment by bartbutenaers** [comment]
Hey Dean,
No problem.   I know the feeling of too much hobby stuff ...
Bart

**Pull request closed without merging**
